-- MySQL Script generated by MySQL Workbench
-- Mon Jul 29 10:57:56 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`dono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dono` (
  `iddono` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`iddono`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`animal` (
  `idanimal` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `datanasc_animal` VARCHAR(45) NULL,
  `dono_iddono` INT NOT NULL,
  PRIMARY KEY (`idanimal`),
  INDEX `fk_animal_dono_idx` (`dono_iddono` ASC) VISIBLE,
  CONSTRAINT `fk_animal_dono`
    FOREIGN KEY (`dono_iddono`)
    REFERENCES `mydb`.`dono` (`iddono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefone` (
  `idtelefone` INT NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `dono_iddono` INT NOT NULL,
  PRIMARY KEY (`idtelefone`),
  INDEX `fk_telefone_dono1_idx` (`dono_iddono` ASC) VISIBLE,
  CONSTRAINT `fk_telefone_dono1`
    FOREIGN KEY (`dono_iddono`)
    REFERENCES `mydb`.`dono` (`iddono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
